name: 'Setup Project'
description: 'Checkout code, setup Node.js, enable Yarn, and install dependencies'

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
      with:
        node-version-file: '.nvmrc'

    - name: Enable corepack
      shell: bash
      run: corepack enable

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Cache Yarn dependencies
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          .yarn/cache
          .yarn/install-state.gz
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable

    - name: Cache built library
      id: cache-lib
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        path: lib
        key: ${{ runner.os }}-lib-${{ hashFiles('src/**/*.{ts,tsx,js,jsx}', 'package.json', 'tsconfig.json') }}
        restore-keys: |
          ${{ runner.os }}-lib-

    - name: Build library (bob build)
      if: steps.cache-lib.outputs.cache-hit != 'true'
      shell: bash
      run: yarn prepare
