# If you want to automatically update fastlane if a new version is available:
#update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.213.0"

default_platform :ios

platform :ios do
  
    desc "Build a new version of MendixNative lib"
  lane :build_mendixnative do |options|
    sh("npm", "ci", "--legacy-peer-deps")
    cocoapods

    build_folder = File.expand_path("../build/mendixnative")
    sh("rm -rf #{build_folder} && mkdir -p #{build_folder}")

    # Building for iOS Simulator
    xcodebuild(
      scheme: "MendixNative",
      sdk: "iphonesimulator",
      xcargs: [
        "ENABLE_BITCODE=YES",
        "OTHER_LDFLAGS='-ObjC -fembed-bitcode'",
        "ONLY_ACTIVE_ARCH=NO",
        "BITCODE_GENERATION_MODE=bitcode",
        "BUILD_DIR=#{build_folder}/library/simulator",
        "-arch x86_64",
        "-arch arm64",
      ].join(" "),
    )

    xcodebuild(
      scheme: "MendixNative",
      sdk: "iphoneos",
      xcargs: [
        "ENABLE_BITCODE=YES",
        "OTHER_LDFLAGS='-ObjC -fembed-bitcode'",
        "ONLY_ACTIVE_ARCH=NO",
        "BITCODE_GENERATION_MODE=bitcode",
        "BUILD_DIR=#{build_folder}/library/iphone",
        "-arch arm64",
      ].join(" "),
    )

    create_xcframework(
      libraries_with_headers_or_dsyms: {
        "#{build_folder}/library/iphone/Release-iphoneos/libMendixNative.a" => {
          headers: "#{build_folder}/library/iphone/Release-iphoneos/include/MendixNative/",
        },
        "#{build_folder}/library/simulator/Release-iphonesimulator/libMendixNative.a" => {
          headers: "#{build_folder}/library/simulator/Release-iphonesimulator/include/MendixNative/",
        },
      },
      output: "#{build_folder}/mendixnative.xcframework",
    )
  end
end
