import Foundation

// MARK: - Paths
let MANIFEST_FILE_NAME = "manifest.json"
let OTA_DIR_NAME = "Ota"

// MARK: - Error Codes
let INVALID_RUNTIME_URL = "INVALID_RUNTIME_URL"
let INVALID_DEPLOY_CONFIG = "INVALID_DEPLOY_CONFIG"
let OTA_ZIP_FILE_MISSING = "OTA_ZIP_FILE_MISSING"
let OTA_UNZIP_DIR_EXISTS = "OTA_UNZIP_DIR_EXISTS"
let OTA_DEPLOYMENT_FAILED = "OTA_DEPLOYMENT_FAILED"
let INVALID_DOWNLOAD_CONFIG = "INVALID_DOWNLOAD_CONFIG"
let OTA_DOWNLOAD_FAILED = "OTA_DOWNLOAD_FAILED"

// MARK: - Download Config Keys
let DOWNLOAD_CONFIG_URL_KEY = "url"

// MARK: - Deploy Config Keys
let DEPLOY_CONFIG_OTA_DEPLOYMENT_ID_KEY = "otaDeploymentID"
let DEPLOY_CONFIG_OTA_PACKAGE_KEY = "otaPackage"
let DEPLOY_CONFIG_EXTRACTION_DIR = "extractionDir"

// MARK: - Manifest Keys
let MANIFEST_OTA_DEPLOYMENT_ID_KEY = "otaDeploymentID"
let MANIFEST_RELATIVE_BUNDLE_PATH_KEY = "relativeBundlePath"
let MANIFEST_APP_VERSION_KEY = "appVersion"

//Checked
