# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  before_all do
    Dir.chdir("../..") do
      sh("npm", "ci", "--legacy-peer-deps")
      # Special hack to work-around alpine linux problem - File.getCanonicalPath is failing without a reason:
      sh("find node_modules -name '*.gradle' -type f -exec sed -i.bak '/canonicalPath/d' {} +")
    end
  end

  desc "Build Mendix Native library"
  lane :build_mendix_native do
    gradle(
      task: ":mendixnative:assembleRelease",
      flags: "-x test",
    )
    copy_artifacts(
      target_path: "../artifacts",
      artifacts: ["./mendixnative/build/outputs/aar/"],
    )
  end
end
